[project]
name = "mcpagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adrià Cabello", email = "adrian.cabello@alumni.esci.upf.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "langfuse>=3.0.1",
    "langgraph>=0.4.8",
    "mcp[cli]>=1.9.3",
    "openai>=1.86.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "websockets>=15.0.1",
]

[project.scripts]
mcpagent = "mcpagent:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
ignore = ["F841", "F811", "F821", "F401"]  # Example: ignore unused imports and line length
